### ISSUE TITLE
Forcing video mode on European wii

### ISSUE THREAD

**Issue by AciliBorek** [ArtemioUrbina/240pTestSuite#12]
This suite forces PAL video mode on my European wii, even when I regionhack it and use the hack to have NTSC video on games. I really don't know where this suite gets its information. My CRT is only NTSC so I have wrong colors with this suite. I think options for different video modes on wii can solve this.

**Comment by ArtemioUrbina** [comment]
The suite reads the options from the Wii configuration. 

Options for video modes are alredy present, you can change them from the MENU and under VIDEO..
