### ISSUE TITLE
Missing build instructions

### ISSUE THREAD

**Issue by Wuerfel21** [ArtemioUrbina/240pTestSuite#13]
There are no build instructions in the repository at all or if there are I can't find them. As the saying goes, a source repository without instructions is worth nothing ;3

In particular, I'm trying to build the megadrive version. Using the ususal SGDK build commmand results in a lot of errors. Is a customized SGDK needed?
```
help.c: In function 'ChangeResolution':
help.c:31:17: error: 'APLAN' undeclared (first use in this function)
  VDP_drawTextBG(APLAN, "Resolution can be changed by", TILE_ATTR(PAL0, 0, 0, 0), 4, (*y)++);
                 ^~~~~
help.c:31:17: note: each undeclared identifier is reported only once for each function it appears in
help.c:31:2: error: too many arguments to function 'VDP_drawTextBG'
  VDP_drawTextBG(APLAN, "Resolution can be changed by", TILE_ATTR(PAL0, 0, 0, 0), 4, (*y)++);
  ^~~~~~~~~~~~~~
In file included from C:/SGDK/inc/tools.h:15:0,
                 from C:/SGDK/inc/genesis.h:15,
                 from help.c:22:
C:/SGDK/inc/vdp_bg.h:323:6: note: declared here
 void VDP_drawTextBG(VDPPlane plane, const char *str, u16 x, u16 y);
      ^~~~~~~~~~~~~~
[...]
```

**Comment by ArtemioUrbina** [comment]
My fault, and I did have it in my TODO list. 

Glad you are interested in building it, I already included the instructions in a BUILD.txt file, and the  branch of the SGDK that is used is now live at https://github.com/ArtemioUrbina/SGDK_1_11_Suite

It is not a custom version at all, it is the main branch, but a snapshot from 2014 (version 1.11).

Why it hasn't been updated? Due to Sega CD support, the current linked library is too big, so I kept it to the point where this issue was obvious.

Best Regards

**Comment by Wuerfel21** [comment]
Ahh, many thanks.

My need to build the suite is gone now though. I was tracking down a nasty bug (ADDQ/SUBQ on An mistakenly setting flags) in an MD emulator I'm writing, that 240p suite was triggering (in a very strange way - video mode was stuck on interlaced (despite not actually being interlaced) because of weird GCC codegen in `VDP_Detect_Interlace`, making it always return true). So I thought it would be handy to have some debugging symbols -> build from source. Managed without them though.

Though I guess I'm glad I could bring this issue to light, too!
Will try and see if I can now get the suite built tomorrow, for the sake of posterity.

**Comment by ArtemioUrbina** [comment]
Glad to read you could sort it out, best regards!
