### ISSUE TITLE
Feature request: Original Xbox or DVD Video version

### ISSUE THREAD

**Issue by rizaumami** [ArtemioUrbina/240pTestSuite#21]
I have ogxbox, and would love to see 240pTestSuite run as native application in it.
The ogxbox has been modded so it's not a problem to display patterns in image/picture format, or run S/NES version on its emulator. But am not sure for the accuracy of the display from the emulators or the custom dashboards.

**Comment by ArtemioUrbina** [comment]
Thank you, do you know of any open source SDK to develop for it and what I would need? 
Running the SNES version would be as good as the SNES emulatror video output is when mapped to the xbox. In general that is usually not very useful.

**Comment by rizaumami** [comment]
Unfortunately I don't have the technical knowledge about it.
Perhaps it's better to just keep this issue open in case someone knowledgeable chime in.

**Comment by ArtemioUrbina** [comment]
There's this one: https://github.com/XboxDev/nxdk

I'll check after publishing all that's on the pipeline, thanks!
