### ISSUE TITLE
SNES Version compile ?!

### ISSUE THREAD

**Issue by kirk33** [ArtemioUrbina/240pTestSuite#24]
I get this error :

Compiling Soundbank ...
@/c/snesdev/devkitsnes/tools/smconv -l -s -o soundbank -v -b 5 samples.it
make: *** [Makefile:84: soundbank.asm] Error 127

Is it missing soundbank.asm ? Thanks.

**Comment by ArtemioUrbina** [comment]
That is automatically generated as stated in the pvsneslib: https://github.com/alekmaul/pvsneslib/wiki/Community-FAQ#soundbank-files-are-missing-in-music-samples

Also be sure to use the recommended pvsneslib-2.2.0 (26/07/2014) as stated in the comment at the start of the main 240pSuite.c file.

**Comment by kirk33** [comment]
Thank you. Do you know where to download pvsneslib-2.2.0 now ?

I have another error. It missing some bmp.
make: *** No rule to make target 'monoscope239.bmp', needed by 'monoscope239.pic'.  Stop.
make: *** No rule to make target 'gillian_b1.bmp', needed by 'gillian_b1.pic'.  Stop.
make: *** No rule to make target 'gillian_b2.bmp', needed by 'gillian_b2.pic'.  Stop.
make: *** No rule to make target 'barcode.bmp', needed by 'barcode.pic'.  Stop.
make: *** No rule to make target 'dissapear.bmp', needed by 'dissapear.pic'.  Stop.

**Comment by ArtemioUrbina** [comment]
It's right here fortunately, in my github:

https://github.com/ArtemioUrbina/pvsneslib-240ptestsuite-fork

I'll check the bmps tomorrow mornimg, sorry

**Comment by ArtemioUrbina** [comment]
Fixed the missing bmp issue, please pull the files. Thanks for bringing this to my attention.

**Comment by kirk33** [comment]
![2023-07-11_044339](https://github.com/ArtemioUrbina/240pTestSuite/assets/84021852/7d93ccae-18d6-4f43-ba54-1d384113435e)
I used your pvsneslib v2.2.0 to compile 240pTestSuite (11-jul-2023). But graphic is corrupted. Any idea ?

**Comment by ArtemioUrbina** [comment]
Yeah, the font is corrupted. Pull the bmp and rebuild, it should be fixed. Thank you

**Comment by kirk33** [comment]
Everything work now ! It can compile and work fine. Thank you very much !
