### ISSUE TITLE
PCE: Menu glitches when using too many string constants

### ISSUE THREAD

**Issue by SteveMaddison** [ArtemioUrbina/240pTestSuite#26]
I was looking at adding some more diagnostics to the PCE version and even managed to do so in a somewhat hackish way. However, I noticed after a while that the options/help/credits menu and the "TG-16" and screen resolution in the bottom right of the screen were getting corrupted. If I remove enough string constants from my code (e.g. statically declared, text for put_string(), etc.) it goes back to normal. I suspect this is due to overwriting something in a particular memory location, certain banks being full, or similar. Being new to PCE development I don't really understand what's happening but maybe someone has experienced this before and can determine the cause (and hopefully solution). To reproduce: add a long string constant to `test_sound.c` for example.

**Comment by ArtemioUrbina** [comment]
you are spot on, and balancing teh text on teh suite is always fun.

Check out the output after building: 
segment usage:

				    USED/FREE
      ZP    $2000-$2015  [  22]       22/ 234
     BSS    $2200-$2A35  [2102]     2102/6090

BANK  0  Base Library 1             6820/1372
BANK  1  Base Library 2/Font        8186/   6
BANK  2  Constants                  8191/   1
BANK  3  User Program               8192/   0

Constants is the bank for strings

**Comment by dshadoff** [comment]
Yes, HuC has its limits.
String constants are all placed into that same bank, and each bank has a limit of 8192 bytes, so there is a limit to how much text is allowed this way.
Data can be manually loaded into a specific bank, but accessing it would end up being manual as well.

I can check with the developers and see whether this has been addressed in a newer version of HuC, but even if it is, there might be some effort involved in porting the code.

I'll update here with what I find out either way.

**Comment by dshadoff** [comment]
I heard back from one of the developers, and the newest release of HuC still has this limitation.

> If you _really_ need that much text or constant data, you need to drop into assembly and put them in the data segment. Of course, if text (or anything else) is in the data segment, then you'll have to bank it in yourself, the compiler/assembler won't do it automagically.

This is roughly what I mentioned above. Unfortunately, this technique needs some custom routines/approaches.

**Comment by ArtemioUrbina** [comment]
Thank you my friend. I believe that's what I did to balance things out years ago, when I added the asm macros to print the help, and move the help text to the data segment:

```
audiosync_00_00:	.db	"AUDIO SYNC"
			.db	0
audiosync_00_01:	.db	"This test flashes the whole screen white for 2"
			.db	0
audiosync_00_02:	.db	"frames, along with a 1khz test tone."
			.db	0
audiosync_00_03:	.db	"You can verify the sync between audio and video"
			.db	0
audiosync_00_04:	.db	"with recording equipment or specialized hardware."
			.db	0
audiosync_00_05:	.db	"- Press I to start/stop the test."
			.db	0
```

**Comment by SteveMaddison** [comment]
Great, thanks for clarifying! I'll see if I can move stuff around, maybe using the help text as an example. And/or just use (a lot) less text... Feel free to close this issue; it's more of a query anyway.

(This would also appear to confirm another suspicion that I had, that if you want to do paging/banking then huc won't do that for you and it needs to be done in assembly.)

**Comment by ArtemioUrbina** [comment]
Possibly got a solution for you: 
While building, change
`pceas -s -raw 240pSuite.s || goto :error`
to
`pceas -O -s -raw 240pSuite.s || goto :error`

You now need to enable optimizations manually.

**Comment by SteveMaddison** [comment]
That seems to use even more of the "Constants" bank, and a bunch of others too. The usage doesn't seem to be affected when adding more constants though, so maybe it's down to padding or something? In any case, the glitching is indeed gone when using that option!

**Comment by ArtemioUrbina** [comment]
Ah yes, Constants should be full when using the option, since all banks are optimized when this is enabled.  i was debugging the compiler to figure out another issue I had last night after I updated huc and it was related.

if you have your code available so I could try and check if the compiler could figure out when that glitching would happen, it would be great so the compiler can tell the user that the space is gone and not glitch. We rather have a tool that fails and tells you where before, it is hard to notice the issue in a build otherwise.

**Comment by SteveMaddison** [comment]
Just add for example to test_sound.c from line 40:

```
#endif

const char *filler[] = {
  "01234567890123456789012345678901234567890123456789",
  "01234567890123456789012345678901234567890123456789",
  "01234567890123456789012345678901234567890123456789",
  "01234567890123456789012345678901234567890123456789",
  ...
};
```
Those are lines of 50 bytes, after about 20 lines/1000 bytes the corruption starts to occur. The effects are slightly different depending where and in which files you add the extra constants.

Can provide a fork/branch with more examples if required, no problem.

**Comment by ArtemioUrbina** [comment]
Thank you, just tested it. 

Yes, it is an issue when the compiler won't tell us when the bank is full I guess. I'll probably look into it later due curiosity, I am no expert.

But due to the optimization (-O) maybe we can fix this by moving the help functions under the comment:

/* This is defined in C to use up the constants bank */

To the same format the helpdata.c ones are made, and huc will now optimize out the constants bank as needed.

**Comment by ArtemioUrbina** [comment]
Update: Yes, that obviously worked. Will do that later if needed, I'll continue to work on the other stuff meanwhile

**Comment by SteveMaddison** [comment]
Nice, that saves a lot of messing around.

**Comment by SteveMaddison** [comment]
Thought I had spoken too soon, I got some minor glitches again after adding more code and constants. But merging your master branch has fixed it so definitely looks like the way to go.
