### ISSUE TITLE
NES not included in downloads

### ISSUE THREAD

**Issue by msbeck** [ArtemioUrbina/240pTestSuite#29]
I don't believe the NES build is included in the downloads at the itch.io page https://artemiourbina.itch.io/240p-test-suite

**Comment by ArtemioUrbina** [comment]
> I don't believe the NES build is included in the downloads at the itch.io page https://artemiourbina.itch.io/240p-test-suite

No, it isn't since it is created and distributed by @pinobatch . It is available at:
https://github.com/pinobatch/240p-test-mini/releases
