### ISSUE TITLE
N64 ROM

### ISSUE THREAD

**Issue by networkfusion** [ArtemioUrbina/240pTestSuite#3]
Hi @ArtemioUrbina . Like the work you are doing here! I have been trying to make this compatible with the latest libdragon version:  https://github.com/N64-tools/cmake-demo-rom/tree/develop-display-testsuite
using this fork: https://github.com/N64-tools/libdragon/tree/develop-displaytest

I am just wondering what you had working when you first built it so that I can (attempt) to get it all working as well...

BTW, I am creating the libdragon and ROM's with VS2019 on windows (and my ultimate goal is to ensure compatibility across platforms, so I would be unsurprised if some of my issues result from that)... also I am on the n64brew discord channel if it helps...

Thanks,

Robin.

**Comment by ArtemioUrbina** [comment]
Hello! First of all, thanks for your interest.

I had all the basics running, here is my build:

[240pSuite-N64Beta.zip](https://github.com/ArtemioUrbina/240pTestSuite/files/4807139/240pSuite-N64Beta.zip)

I believe I modified a few things in the SDK, if you need a zip of my SDK folder let me know and I'll upload it.

I am also in the discord, you can ring me anytime

**Comment by CanadianJeff** [comment]
could we get a compiled version from a newer commit?

**Comment by ArtemioUrbina** [comment]
Sur
[240pSuiteN64-01-2022.zip](https://github.com/ArtemioUrbina/240pTestSuite/files/8111621/240pSuiteN64-01-2022.zip)
e

**Comment by CanadianJeff** [comment]
ok so this actually fails to run on real hardware but boots just fine in project64

**Comment by ArtemioUrbina** [comment]
> ok so this actually fails to run on real hardware but boots just fine in project64

How are you running it? It has only been tested on real HW with an everdrive, and I just downloaded the above zip and tested it on my console.

It worked fine.

**Comment by CanadianJeff** [comment]
oh I have the 64drive HW2 if that means anything

**Comment by ArtemioUrbina** [comment]
> oh I have the 64drive HW2 if that means anything

Sorry, I don't have one to test... so it is probably a problem with the flash cart, since it works on everdrive and emulation.

**Comment by CanadianJeff** [comment]
I confirmed that it works on Project64 so the rom is fine my 64drive shows 240pSuite.z64 Boot CIC as 6102 I do have Force Region set to Auto and not PAL or NTSC that might be why?

**Comment by ArtemioUrbina** [comment]
> I confirmed that it works on Project64 so the rom is fine my 64drive shows 240pSuite.z64 Boot CIC as 6102 I do have Force Region set to Auto and not PAL or NTSC that might be why?

I have no idea, sorry. I don't own that flash cart.

**Comment by CanadianJeff** [comment]
would it be possible to find out why its not working on the 64drive but it does on everdrive??? what would be the likely cause of it not working

**Comment by ArtemioUrbina** [comment]
Contacting the manufacturer and asking why it isn't would be my first guess.

**Comment by CanadianJeff** [comment]
well the manufacturer is kinda busy so maybe we can figure it out

**Comment by ArtemioUrbina** [comment]
I have no idea what to look for.

**Comment by CanadianJeff** [comment]
someone is claiming to have an open source menu driver for the 64drive I think we just need to get our hands on it

**Comment by CanadianJeff** [comment]
does this ROM have a proper header CRC and checksum in it?

**Comment by ArtemioUrbina** [comment]
Since it is a beta build that has not been released, I never looked into it. 

I assume you didn't run the utility to check? Here is the oputput:

Real N64 CRC Tool V2 [By RaO 1999/2000] - Check CRC's

FileName     : 240pSuite.z64
ROM Title    : 240p Test Suite     
Type         : CIC-NUS-6102
CRC's        : $F56FDCAF, $AAE42F4A [OK]

So yes, it has a proper header and CRC to the best of my knowledge.

There is no debug info that could be shown at all, if the ROM could boot it would boot. You can check the code, it simply draws to screen.

**Comment by CanadianJeff** [comment]
it's kinda odd because I can boot linux.z64 over 64drive's USB which bypass the menu but can not boot your 240pSuite which I do not understand

**Comment by ArtemioUrbina** [comment]
Neither do I. Did you try the option in the Quick Start Guide? You should contact the flash cart manufacturer

**Comment by CanadianJeff** [comment]
why do you keep repeating that I don't think the flash cart manufacturer cares about us end users they even halted making more of the cart due to chip shortages

**Comment by ArtemioUrbina** [comment]
Because I have no way to help you with a hardware issue of hardware I don't have access to. Sorry.
