### ISSUE TITLE
new megacd2 bios dump (unknown crc report)

### ISSUE THREAD

**Issue by TwistedTom** [ArtemioUrbina/240pTestSuite#7]
Have dumped euro v2.11 bios [(submitted to mame)](https://github.com/mamedev/mame/pull/8420)

![euro_211](https://user-images.githubusercontent.com/37988779/129125786-c5ef6663-b3b5-4e14-933e-112ef89839ef.jpg)

**Comment by ArtemioUrbina** [comment]
Ahh awesome! Thank you for submitting it. I will add it to the suite now. On case somebody else finds this message and has no alternate dump method:
https://www.youtube.com/watch?v=poW1hMniYI0

**Comment by ArtemioUrbina** [comment]
Here is the RC that should detect this BIOS, if possible please test it:
Cart: http://junkerhq.net/240pTestSuite/_Beta/240pSuite-1.23d.bin
Sega CD:  http://junkerhq.net/240pTestSuite/_Beta/240pSuite-1.23d-SCD.zip
[240pSuite-1.23d.zip](https://github.com/ArtemioUrbina/240pTestSuite/files/6973317/240pSuite-1.23d.zip)
[240pSuite-1.23d-SCD.zip](https://github.com/ArtemioUrbina/240pTestSuite/files/6973318/240pSuite-1.23d-SCD.zip)

**Comment by TwistedTom** [comment]
Cart version test:

![fixed](https://user-images.githubusercontent.com/37988779/129250934-2d580c2c-9820-4a15-9f92-32f062107273.jpg)

Looks good !

**Comment by TwistedTom** [comment]
> In case somebody else finds this message and has no alternate dump method:
> https://www.youtube.com/watch?v=poW1hMniYI0

Another way is [mcdBiosDumper](https://github.com/fabiodl/mcdBiosDumper), dumps serially via controller 2 port pin 6.
This is useful for older flash carts (Everdrive MD etc.) which don't have bram function. Just need a cheap usb-to-tll converter.
