### ISSUE TITLE
[Feature] Option to stretch horizontally to 720 for Wii

### ISSUE THREAD

**Issue by ChainSwordCS** [ArtemioUrbina/240pTestSuite#8]
Hello! I'd like to say for reference that I'm currently conducting thorough tests on how the Wii U outputs and upscales Wii content (and how bad it is...)

I don't know how well known it is, but the Wii as a matter of fact outputs with a width of 720, both in Progressive and Interlaced modes. This is the case for the Wii U yes, but I tested and verified the original Wii outputs this resolution also.

It's actually somewhat of a feature... In summary, the framebuffer is (more or less) hard-limited to a width of 640 and a height of 528. However, the image can be stretched vertically by(?) the XFB to a height of 576, and it can be stretched horizontally by(?) the VI to a width of 720.

Also, there is already an Option to stretch vertically to 288 / 576 on Wii (but it's impossible to maintain the 1:1 pixel-aspect). My request is for a similar feature to stretch horizontally to 720 (still impossible to maintain the 1:1 pixel-aspect).

This feature would allow for better determination of horizontal overscan; I believe right now the program is outputting 640x480 and the Wii is naturally letter-boxing it, so the program would always show an "overscan" of 0 because horizontally all 640 pixels are obviously in frame. (In theory... I haven't tested this on an original Wii just yet but I have tested on Wii U.)

Side notes:
- I don't know whether or not this whole system also applies to the GameCube, they are quite similar hardware after all, but I think it _might_ output 640 pixels wide all the time unlike the Wii. I will test and confirm this on console and get back to you.
- If you want to see some of my empirical testing results and data, I can link a Google Document, but it's **very** unfinished at the moment.

**Comment by ArtemioUrbina** [comment]
Hello ChainSwordCS,

Yes it is possible to do so, here is a build with it under options. As you know it does look terrible and renders all geometry patterns useless, so I might hide this option from the main release (to be enabled only form the xml or something of the sort)

Let me know if this is what you expect so I can close this.

https://we.tl/t-IhBwPschp8

**Comment by ChainSwordCS** [comment]
After some testing, it does work as expected! Awesome, thanks a lot!

Personally I think it might be okay to show the option, maybe next to the option which scales it vertically to fit 576 lines, but it's up to you.

.

Also, it might be nice if there was an overscan testing feature which resized the game window based on the numbers input, to get a more accurate number of pixels of overscan... Or maybe a way to move the 'game window' horizontally, so it's on the far left or right side of the 720x480 plane while maintaining square pixels, but I don't know if that's actually possible.

At any rate, that might fit better under a different Issue or feature request.

I don't know how easy or difficult it would be to implement and it would be an incredibly niche feature. I'm gonna estimate 99% or maybe 100% of retail Wii games don't stretch to 720. Some homebrew might, like Nintendont can, but Nintendont has a manually adjustable width and other homebrew applications likely have or should have adjustable width too.

**Comment by ArtemioUrbina** [comment]
Wouldn't this, and the purposed, features be better as modes under the grid pattern, and not general options? They serve little purpose elsewhere, no?
